name: Discord Idle Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - env:
          DC_TOKEN: ${{ secrets.DC_TOKEN }}
          ONLINE_SECONDS: 14400
        run: npm start
