name: Sync Private Repo

on:
  schedule:
    - cron: "0 */6 * * *" # Her 6 saatte bir çalışır
  workflow_dispatch: # Manuel olarak da çalıştırma seçeneği ekler

jobs:
  sync-private-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu Checkout Et
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Private Repo'yu Klonla
        run: |
          git clone https://github.com/${{ secrets.PRIVATE_REPO_OWNER }}/PRIVATE_REPO.git private-repo
        env:
          GIT_TERMINAL_PROMPT: 0
          GIT_ASKPASS: /bin/echo
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Private Repo'dan Kodları Çalıştır
        run: |
          cd private-repo
          # Örnek: script çalıştır
          npm install
          npm run build
