name: Sync Private Repo

on:
  schedule:
    - cron: "0 */6 * * *" # Her 6 saatte bir otomatik çalışır
  workflow_dispatch: # Manuel olarak başlatma seçeneği ekler

jobs:
  sync-private-repo:
    runs-on: ubuntu-latest

    steps:
      # 1. Public Repo'yu Checkout Et
      - name: Public Repo'yu Checkout Et
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Private Repo'yu Klonla
      - name: Private Repo'yu Klonla
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/${{ secrets.PRIVATE_REPO_OWNER }}/selfbot.git private-repo

      # 3. Private Repo İçindeki Kodları Çalıştır
      - name: Private Repo Kodlarını Çalıştır
        run: |
          cd private-repo
          npm install
          npm run build
