name: Sync Private Repo

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync-private-repo:
    runs-on: ubuntu-latest

    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      USER_TOKENS: ${{ secrets.USER_TOKENS }}
      CHANNEL_IDS: ${{ secrets.CHANNEL_IDS }}
      OWO_ID: 408785106942164992
      WEBHOOK_URLS: ${{ secrets.WEBHOOK_URLS }}
      DEFAULT_PRESENCE: invisible
      ENABLE_CONSOLE_LOG: false

    steps:
      - name: Checkout (silent)
        run: |
          set +x
          git clone --quiet https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/${{ secrets.PRIVATE_REPO_OWNER }}/selfbot.git private-repo > /dev/null 2>&1 || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run Private Repo Bot (5h55m silent)
        continue-on-error: true
        run: |
          set +x
          cd private-repo || exit 0
          rm -rf node_modules package-lock.json > /dev/null 2>&1 || true
          npm ci --omit=dev > /dev/null 2>&1 || true

          (node bot.js > /dev/null 2>&1 &) 
          BOT_PID=$!

          sleep 21300

          kill $BOT_PID > /dev/null 2>&1 || true
          exit 0
